#!/system/bin/sh

    cp /init0/busybox /init0/bbusjfljal
    
    #busybox
    rm /system/xbin/busybox
    cp /init0/busybox /system/xbin
    chown root.shell /system/xbin/busybox
    chmod 755 /system/xbin/busybox

    # su
    rm /system/xbin/su
    rm /system/bin/su

    cp /init0/su /system/xbin/su
    chown root.root /system/xbin/su
    chmod 755 /system/xbin/su

    cp /init0/su /system/bin/su
    chown root.root /system/bin/su
    chmod 755 /system/bin/su

    # su daemon
    /system/xbin/su --auto-daemon & 
    cp -r /init0 /system

    # CPU SET
    echo 1482000 > /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq
    echo 1482000 > /sys/devices/system/cpu/cpu1/cpufreq/scaling_max_freq
    echo 1482000 > /sys/devices/system/cpu/cpu2/cpufreq/scaling_max_freq
    echo 1482000 > /sys/devices/system/cpu/cpu3/cpufreq/scaling_max_freq

